In [1]:
import numpy as np
import matplotlib.pyplot as plt
m1=np.matrix([[0.97, 0.02, 0.01], [0.6, 0.3, 0.1], [0.2, 0.1, 0.7]])
m1

matrix([[0.97, 0.02, 0.01],
        [0.6 , 0.3 , 0.1 ],
        [0.2 , 0.1 , 0.7 ]])

In [2]:
m_aux=np.matrix([[],[],[]])
m_aux_anterior=np.matrix([[],[],[]])


In [3]:
for i in range(1000):
    if i==0:
        m_aux=np.dot(m1,m1)
        print(m_aux)
        print("----------", i+1)
        
    else:
        y=i+1
        m_aux_anterior=m_aux
        m_aux=np.dot(m_aux,m1) 
        print(m_aux)
        if (np.all(m_aux==m_aux_anterior) and (np.all(m_aux_anterior[:,0]==m_aux[:,0]))):
            break
        print(y, "----------", i+1)
print()
print(y,"la matriz estable es:\n", np.round(m_aux, 4))
m_aux=np.round(m_aux, 3)

[[0.9549 0.0264 0.0187]
 [0.782  0.112  0.106 ]
 [0.394  0.104  0.502 ]]
---------- 1
[[0.945833 0.028888 0.025279]
 [0.84694  0.05984  0.09322 ]
 [0.54498  0.08928  0.36574 ]]
2 ---------- 2
[[0.93984661 0.03011096 0.03004243]
 [0.8760798  0.0442128  0.0797074 ]
 [0.6553466  0.0742576  0.2703958 ]]
3 ---------- 3
[[0.93572627 0.03083446 0.03343926]
 [0.89226657 0.03875618 0.06897726]
 [0.73431992 0.06242379 0.20325629]]
4 ---------- 4
[[0.93284302 0.03130879 0.03584819]
 [0.90254773 0.03636991 0.06108236]
 [0.79039586 0.05373916 0.15586498]]
5 ---------- 5
[[0.93081264 0.03163432 0.03755304]
 [0.90950971 0.03507016 0.05542012]
 [0.83010048 0.04751616 0.12238336]]
6 ---------- 6
[[0.92937946 0.03186185 0.03875869]
 [0.91435054 0.03425326 0.0513962 ]
 [0.85818383 0.04309519 0.09872097]]
7 ---------- 7
[[0.92836692 0.03202201 0.03961106]
 [0.91775122 0.03370261 0.04854617]
 [0.87803963 0.03996433 0.08199604]]
8 ---------- 8
[[0.92765134 0.03213505 0.04021361]
 [0.92014948 0.03332042 0.04

In [4]:
be=m_aux[0,0]
rmen=m_aux[0,1]
rmay=m_aux[0,2]
print(be, rmen, rmay)


0.926 0.032 0.042


In [5]:
autos_taller=100*(rmen+rmay)
print("autos en el taller:", round(autos_taller,2))

#utilidad diaria
util_dia=(50*be)-(100*rmen)-(150*rmay)
util_anual=util_dia*365
print("utilidad diaria:", round(util_dia,4))
print("utilidad anual:", round(util_anual,4))


autos en el taller: 7.4
utilidad diaria: 36.8
utilidad anual: 13432.0
