In [10]:
import numpy as np
m1=np.matrix([[0.3,0.7],[0.99,0.01]])
m1

matrix([[0.3 , 0.7 ],
        [0.99, 0.01]])

In [8]:
#Matriz auxiliar y una aux anterior 
m_aux=np.matrix([[],[]])
m_aux_anterior=np.matrix([[],[]])

In [9]:
#Iterar para encontrar matriz estable
import math as m


for i in range(1000):
    if i == 0:
        m_aux = np.dot(m1, m1)  
        print(m_aux)
        print("1----------------", i + 1)
        
    else:
        y = i + 1
        m_aux_anterior = m_aux
        m_aux = np.dot(m_aux, m1)
        print(m_aux)
        print("1----------------", i + 1)
        #DEbemos condicionar para encontrar la matriz estable 
        if (np.all(m_aux == m_aux_anterior) and
            np.all(m_aux_anterior[:, 0] == m_aux[:, 0]) and
          np.all(m_aux_anterior[:, 1] == m_aux[:, 1])):
            print("Matriz estable")
            break
   
       

[[0.783  0.217 ]
 [0.3069 0.6931]]
1---------------- 1
[[0.44973  0.55027 ]
 [0.778239 0.221761]]
1---------------- 2
[[0.6796863  0.3203137 ]
 [0.45301509 0.54698491]]
1---------------- 3
[[0.52101645 0.47898355]
 [0.67741959 0.32258041]]
1---------------- 4
[[0.63049865 0.36950135]
 [0.52258048 0.47741952]]
1---------------- 5
[[0.55495593 0.44504407]
 [0.62941947 0.37058053]]
1---------------- 6
[[0.60708041 0.39291959]
 [0.55570057 0.44429943]]
1---------------- 7
[[0.57111452 0.42888548]
 [0.60656661 0.39343339]]
1---------------- 8
[[0.59593098 0.40406902]
 [0.57146904 0.42853096]]
1---------------- 9
[[0.57880762 0.42119238]
 [0.59568636 0.40431364]]
1---------------- 10
[[0.59062274 0.40937726]
 [0.57897641 0.42102359]]
1---------------- 11
[[0.58247031 0.41752969]
 [0.59050628 0.40949372]]
1---------------- 12
[[0.58809549 0.41190451]
 [0.58255067 0.41744933]]
1---------------- 13
[[0.58421411 0.41578589]
 [0.58804004 0.41195996]]
1---------------- 14
[[0.58689226 0.41310774]
